### ISSUE TITLE
Possible Typo in Exclude Uncommon Names in READme 

### ISSUE THREAD

**Issue by OlyBar** [TimeMagazineLabs/babynames#9]
min: Don't include names that don't show up at least this many **time** in at least one year. Ex: --min=25. Default is 0.

Should the statement instead read?
min: Don't include names that don't show up at least this many **time(S)** in at least one year. Ex: --min=25. Default is 0.

This is my very first time contributing to open source, so if you have any advice or if I'm doing anything wrong, please let me know! Thank you :)

**Comment by wilson428** [comment]
Very very belated, thanks!
